<a href="https://colab.research.google.com/github/jtmeawno1/bsc_dpdm22/blob/main/Performance_Evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets
iris_data = datasets.load_iris()
#	sepal: กลีบเลี้ยง #petal:กลีบดอก

In [2]:
X = iris_data['data']
y = iris_data['target']

In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold, cross_val_score

In [4]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, KFold

In [5]:
model = DecisionTreeClassifier()

# Define the k-fold cross validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Train and evaluate the model using 10-fold cross validation
scores = cross_val_score(model, X, y, cv=kf)

# Print the average accuracy and standard deviation across all folds
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.94 (+/- 0.11)

In [6]:
model = DecisionTreeClassifier(max_depth=2)

# Define the k-fold cross validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Train and evaluate the model using 10-fold cross validation
scores = cross_val_score(model, X, y, cv=kf)

# Print the average accuracy and standard deviation across all folds
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.95 (+/- 0.12)

In [7]:
from sklearn.model_selection import LeaveOneOut

In [8]:
model = DecisionTreeClassifier(max_depth=2)

# Define the k-fold cross validation
LOO = LeaveOneOut()

# Train and evaluate the model using 10-fold cross validation
scores = cross_val_score(model, X, y, cv=LOO)

# Print the average accuracy and standard deviation across all folds
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.95 (+/- 0.42)

In [9]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

transform numpy array to dataframe

In [11]:
import pandas as pd

In [12]:
columns = iris_data['feature_names']
X_df = pd.DataFrame(X, columns=columns)

In [13]:
X_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [14]:
X_df['label']=y

In [15]:
X_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [16]:
shuffled_df = X_df.sample(frac=1,random_state=6)
shuffled_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
4,5.0,3.6,1.4,0.2,0
116,6.5,3.0,5.5,1.8,2
2,4.7,3.2,1.3,0.2,0
23,5.1,3.3,1.7,0.5,0
123,6.3,2.7,4.9,1.8,2
...,...,...,...,...,...
148,6.2,3.4,5.4,2.3,2
79,5.7,2.6,3.5,1.0,1
109,7.2,3.6,6.1,2.5,2
106,4.9,2.5,4.5,1.7,2
138,6.0,3.0,4.8,1.8,2

In [17]:
shuffled_df['fold']=15*[1,2,3,4,5,6,7,8,9,10]

In [18]:
shuffled_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label,fold
4,5.0,3.6,1.4,0.2,0,1
116,6.5,3.0,5.5,1.8,2,2
2,4.7,3.2,1.3,0.2,0,3
23,5.1,3.3,1.7,0.5,0,4
123,6.3,2.7,4.9,1.8,2,5
...,...,...,...,...,...,...
148,6.2,3.4,5.4,2.3,2,6
79,5.7,2.6,3.5,1.0,1,7
109,7.2,3.6,6.1,2.5,2,8
106,4.9,2.5,4.5,1.7,2,9
138,6.0,3.0,4.8,1.8,2,10

# HW6 วนลูปทำ 10-fold cross validation

In [19]:
import numpy as np

In [20]:
# Split the data into features and target | แบ่งข้อมูลออกเป็น features,target
X = shuffled_df.drop('label', axis=1)
y = shuffled_df['label']

In [21]:
# Define a cross-validation object with the specified number of folds | แบ่งเป็น 10 KFold
kfold = KFold(n_splits=10 ,shuffle=True, random_state=6)

# Loop over the folds | วนลูปแต่ละ fold
for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y)): 
    # Get the training and testing data for the current fold
    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_test, y_test = X.iloc[test_idx], y.iloc[test_idx]

    # Create a decision tree classifier object
    dtc = DecisionTreeClassifier()
    
    # Fit the model on the training data
    dtc.fit(X_train, y_train)
    
    # Evaluate the model on the testing data
    scores = cross_val_score(dtc, X_test, y_test) 
    
    # Print the cross-validation score and the data for the current fold
    print(f"Fold: {fold+1}")
    print("Mean accuracy: %0.2f (+/- %0.2f)" % (np.mean(scores), np.std(scores) * 2))
    print(shuffled_df[shuffled_df['fold'] == fold+1])
    print()

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(

Fold: 1
Mean accuracy: 0.93 (+/- 0.27)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
4                  5.0               3.6                1.4               0.2
127                6.1               3.0                4.9               1.8
37                 4.9               3.6                1.4               0.1
45                 4.8               3.0                1.4               0.3
17                 5.1               3.5                1.4               0.3
118                7.7               2.6                6.9               2.3
83                 6.0               2.7                5.1               1.6
89                 5.5               2.5                4.0               1.3
98                 5.1               2.5                3.0               1.1
76                 6.8               2.8                4.8               1.4
41                 4.5               2.3                1.3               0.3
90                 5.5               2.6                4.4               1.2
43                 5.0               3.5                1.6               0.6
86                 6.7               3.1                4.7               1.5
75                 6.6               3.0                4.4               1.4

     label  fold
4        0     1
127      2     1
37       0     1
45       0     1
17       0     1
118      2     1
83       1     1
89       1     1
98       1     1
76       1     1
41       0     1
90       1     1
43       0     1
86       1     1
75       1     1

Fold: 2
Mean accuracy: 0.87 (+/- 0.33)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
116                6.5               3.0                5.5               1.8
81                 5.5               2.4                3.7               1.0
120                6.9               3.2                5.7               2.3
59                 5.2               2.7                3.9               1.4
103                6.3               2.9                5.6               1.8
117                7.7               3.8                6.7               2.2
60                 5.0               2.0                3.5               1.0
84                 5.4               3.0                4.5               1.5
9                  4.9               3.1                1.5               0.1
33                 5.5               4.2                1.4               0.2
22                 4.6               3.6                1.0               0.2
145                6.7               3.0                5.2               2.3
28                 5.2               3.4                1.4               0.2
15                 5.7               4.4                1.5               0.4
1                  4.9               3.0                1.4               0.2

     label  fold
116      2     2
81       1     2
120      2     2
59       1     2
103      2     2
117      2     2
60       1     2
84       1     2
9        0     2
33       0     2
22       0     2
145      2     2
28       0     2
15       0     2
1        0     2

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(

Fold: 3
Mean accuracy: 0.87 (+/- 0.33)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
2                  4.7               3.2                1.3               0.2
115                6.4               3.2                5.3               2.3
44                 5.1               3.8                1.9               0.4
16                 5.4               3.9                1.3               0.4
71                 6.1               2.8                4.0               1.3
121                5.6               2.8                4.9               2.0
99                 5.7               2.8                4.1               1.3
142                5.8               2.7                5.1               1.9
104                6.5               3.0                5.8               2.2
56                 6.3               3.3                4.7               1.6
35                 5.0               3.2                1.2               0.2
70                 5.9               3.2                4.8               1.8
85                 6.0               3.4                4.5               1.6
125                7.2               3.2                6.0               1.8
25                 5.0               3.0                1.6               0.2

     label  fold
2        0     3
115      2     3
44       0     3
16       0     3
71       1     3
121      2     3
99       1     3
142      2     3
104      2     3
56       1     3
35       0     3
70       1     3
85       1     3
125      2     3
25       0     3

Fold: 4
Mean accuracy: 0.93 (+/- 0.27)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
23                 5.1               3.3                1.7               0.5
135                7.7               3.0                6.1               2.3
0                  5.1               3.5                1.4               0.2
13                 4.3               3.0                1.1               0.1
61                 5.9               3.0                4.2               1.5
6                  4.6               3.4                1.4               0.3
100                6.3               3.3                6.0               2.5
132                6.4               2.8                5.6               2.2
112                6.8               3.0                5.5               2.1
140                6.7               3.1                5.6               2.4
82                 5.8               2.7                3.9               1.2
69                 5.6               2.5                3.9               1.1
19                 5.1               3.8                1.5               0.3
31                 5.4               3.4                1.5               0.4
62                 6.0               2.2                4.0               1.0

     label  fold
23       0     4
135      2     4
0        0     4
13       0     4
61       1     4
6        0     4
100      2     4
132      2     4
112      2     4
140      2     4
82       1     4
69       1     4
19       0     4
31       0     4
62       1     4

Fold: 5
Mean accuracy: 0.80 (+/- 0.33)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
123                6.3               2.7                4.9               1.8
74                 6.4               2.9                4.3               1.3
55                 5.7               2.8                4.5               1.3
133                6.3               2.8                5.1               1.5
46                 5.1               3.8                1.6               0.2
111                6.4               2.7                5.3               1.9
94                 5.6               2.7                4.2               1.3
147                6.5               3.0                5.2               2.0
21                 5.1               3.7                1.5               0.4
36                 5.5               3.5                1.3               0.2
141                6.9               3.1                5.1               2.3
40                 5.0               3.5                1.3               0.3
63                 6.1               2.9                4.7               1.4
130                7.4               2.8                6.1               1.9
80                 5.5               2.4                3.8               1.1

     label  fold
123      2     5
74       1     5
55       1     5
133      2     5
46       0     5
111      2     5
94       1     5
147      2     5
21       0     5
36       0     5
141      2     5
40       0     5
63       1     5
130      2     5
80       1     5

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(

Fold: 6
Mean accuracy: 0.80 (+/- 0.53)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
96                 5.7               2.9                4.2               1.3
119                6.0               2.2                5.0               1.5
72                 6.3               2.5                4.9               1.5
128                6.4               2.8                5.6               2.1
12                 4.8               3.0                1.4               0.1
18                 5.7               3.8                1.7               0.3
88                 5.6               3.0                4.1               1.3
65                 6.7               3.1                4.4               1.4
47                 4.6               3.2                1.4               0.2
7                  5.0               3.4                1.5               0.2
11                 4.8               3.4                1.6               0.2
78                 6.0               2.9                4.5               1.5
126                6.2               2.8                4.8               1.8
8                  4.4               2.9                1.4               0.2
148                6.2               3.4                5.4               2.3

     label  fold
96       1     6
119      2     6
72       1     6
128      2     6
12       0     6
18       0     6
88       1     6
65       1     6
47       0     6
7        0     6
11       0     6
78       1     6
126      2     6
8        0     6
148      2     6

Fold: 7
Mean accuracy: 0.87 (+/- 0.53)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
134                6.1               2.6                5.6               1.4
105                7.6               3.0                6.6               2.1
87                 6.3               2.3                4.4               1.3
64                 5.6               2.9                3.6               1.3
52                 6.9               3.1                4.9               1.5
38                 4.4               3.0                1.3               0.2
3                  4.6               3.1                1.5               0.2
73                 6.1               2.8                4.7               1.2
113                5.7               2.5                5.0               2.0
107                7.3               2.9                6.3               1.8
122                7.7               2.8                6.7               2.0
149                5.9               3.0                5.1               1.8
66                 5.6               3.0                4.5               1.5
68                 6.2               2.2                4.5               1.5
79                 5.7               2.6                3.5               1.0

     label  fold
134      2     7
105      2     7
87       1     7
64       1     7
52       1     7
38       0     7
3        0     7
73       1     7
113      2     7
107      2     7
122      2     7
149      2     7
66       1     7
68       1     7
79       1     7

Fold: 8
Mean accuracy: 0.73 (+/- 0.27)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
39                 5.1               3.4                1.5               0.2
51                 6.4               3.2                4.5               1.5
102                7.1               3.0                5.9               2.1
146                6.3               2.5                5.0               1.9
27                 5.2               3.5                1.5               0.2
20                 5.4               3.4                1.7               0.2
101                5.8               2.7                5.1               1.9
139                6.9               3.1                5.4               2.1
131                7.9               3.8                6.4               2.0
42                 4.4               3.2                1.3               0.2
67                 5.8               2.7                4.1               1.0
50                 7.0               3.2                4.7               1.4
144                6.7               3.3                5.7               2.5
110                6.5               3.2                5.1               2.0
109                7.2               3.6                6.1               2.5

     label  fold
39       0     8
51       1     8
102      2     8
146      2     8
27       0     8
20       0     8
101      2     8
139      2     8
131      2     8
42       0     8
67       1     8
50       1     8
144      2     8
110      2     8
109      2     8

Fold: 9
Mean accuracy: 1.00 (+/- 0.00)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
137                6.4               3.1                5.5               1.8
92                 5.8               2.6                4.0               1.2
30                 4.8               3.1                1.6               0.2
95                 5.7               3.0                4.2               1.2
34                 4.9               3.1                1.5               0.2
58                 6.6               2.9                4.6               1.3
14                 5.8               4.0                1.2               0.2
129                7.2               3.0                5.8               1.6
91                 6.1               3.0                4.6               1.4
48                 5.3               3.7                1.5               0.2
10                 5.4               3.7                1.5               0.2
5                  5.4               3.9                1.7               0.4
143                6.8               3.2                5.9               2.3
26                 5.0               3.4                1.6               0.4
106                4.9               2.5                4.5               1.7

     label  fold
137      2     9
92       1     9
30       0     9
95       1     9
34       0     9
58       1     9
14       0     9
129      2     9
91       1     9
48       0     9
10       0     9
5        0     9
143      2     9
26       0     9
106      2     9

Fold: 10
Mean accuracy: 0.93 (+/- 0.27)
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
53                 5.5               2.3                4.0               1.3
32                 5.2               4.1                1.5               0.1
93                 5.0               2.3                3.3               1.0
49                 5.0               3.3                1.4               0.2
54                 6.5               2.8                4.6               1.5
108                6.7               2.5                5.8               1.8
29                 4.7               3.2                1.6               0.2
97                 6.2               2.9                4.3               1.3
136                6.3               3.4                5.6               2.4
24                 4.8               3.4                1.9               0.2
124                6.7               3.3                5.7               2.1
57                 4.9               2.4                3.3               1.0
114                5.8               2.8                5.1               2.4
77                 6.7               3.0                5.0               1.7
138                6.0               3.0                4.8               1.8

     label  fold
53       1    10
32       0    10
93       1    10
49       0    10
54       1    10
108      2    10
29       0    10
97       1    10
136      2    10
24       0    10
124      2    10
57       1    10
114      2    10
77       1    10
138      2    10

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(

In [22]:
X = shuffled_df.drop('label', axis=1)
y = shuffled_df['label']
# Create a decision tree classifier
dt = DecisionTreeClassifier()

# Define the number of folds for K-fold cross-validation
k = 10

# Define the K-fold cross-validation object
kf = KFold(n_splits=k, shuffle=True, random_state=6)

# Loop over each fold and train a decision tree on the training data
for i,(train_index, test_index) in enumerate(kf.split(X)): # เป็นตัวที่เท่าไหรของ list
    # Extract the training and test data for this fold
    X_train, y_train = X.iloc[train_index], y.iloc[train_index]
    X_test, y_test = X.iloc[test_index], y.iloc[test_index]
    
    # Fit the decision tree on the training data for this fold
    dt.fit(X_train, y_train)
    
    # Evaluate the decision tree on the test data for this fold
    accuracy = dt.score(X_test, y_test)
    
    # Print the accuracy for this fold
    print(f"Fold {i+1}: Accuracy = {accuracy:.2f}")

Fold 1: Accuracy = 1.00
Fold 2: Accuracy = 1.00
Fold 3: Accuracy = 1.00
Fold 4: Accuracy = 0.93
Fold 5: Accuracy = 0.93
Fold 6: Accuracy = 0.87
Fold 7: Accuracy = 1.00
Fold 8: Accuracy = 0.93
Fold 9: Accuracy = 0.87
Fold 10: Accuracy = 0.87

# เฉลย HW6

In [30]:
from sklearn.metrics import accuracy_score 
import numpy as np

In [24]:
test_fold  = 1 # กำหนด fold ไหนเป็น test

In [25]:
test_data = shuffled_df[shuffled_df['fold']==test_fold] # แบ่ง row
training_data = shuffled_df[shuffled_df['fold']!=test_fold]

In [26]:
X_test = test_data.iloc[:, :-2] # แบ่ง f
y_test = test_data.iloc[:, -2]
X_train =training_data.iloc[:, :-2]
y_train = training_data.iloc[:, -2]

In [27]:
model = DecisionTreeClassifier(max_depth=2)

model.fit(X_train,y_train)

y_predict = model.predict(X_test)

In [28]:
acc = accuracy_score(y_test,y_predict)
print(f'accuracy of fold {test_fold} = {acc}')

accuracy of fold 1 = 0.8666666666666667

In [31]:
acc_fold  = []
for test_fold in range(1,11):
  test_data = shuffled_df[shuffled_df['fold']==test_fold] 
  training_data = shuffled_df[shuffled_df['fold']!=test_fold]

  X_test = test_data.iloc[:, :-2] 
  y_test = test_data.iloc[:, -2]
  X_train =training_data.iloc[:, :-2]
  y_train = training_data.iloc[:, -2]

  model = DecisionTreeClassifier(max_depth=2)
  model.fit(X_train,y_train)
  y_predict = model.predict(X_test)

  acc = accuracy_score(y_test,y_predict)
  print(f'accuracy of fold {test_fold} = {acc}')
  acc_fold.append(acc)
  
print(f'\naverage accuracy = {np.mean(acc)}')

accuracy of fold 1 = 0.8666666666666667
accuracy of fold 2 = 1.0
accuracy of fold 3 = 0.9333333333333333
accuracy of fold 4 = 1.0
accuracy of fold 5 = 0.9333333333333333
accuracy of fold 6 = 0.9333333333333333
accuracy of fold 7 = 0.9333333333333333
accuracy of fold 8 = 1.0
accuracy of fold 9 = 0.8666666666666667
accuracy of fold 10 = 0.9333333333333333

average accuracy = 0.9333333333333333

# add Precision & Recall from ChatGPT

In [32]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import precision_score, recall_score

# Load the iris dataset
iris = load_iris()

# Define the decision tree model
model = DecisionTreeClassifier()

# Define the k-fold cross validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Train and evaluate the model using 10-fold cross validation
precision_scores = []
recall_scores = []
for train_idx, test_idx in kf.split(iris.data, iris.target):
    # Get the training and testing data for this fold
    X_train, y_train = iris.data[train_idx], iris.target[train_idx]
    X_test, y_test = iris.data[test_idx], iris.target[test_idx]

    # Train the model on the training data for this fold
    model.fit(X_train, y_train)

    # Predict the labels for the testing data for this fold
    y_pred = model.predict(X_test)

    # Calculate the precision and recall for this fold
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')

    # Add the precision and recall scores to the lists for all folds
    precision_scores.append(precision)
    recall_scores.append(recall)

# Print the average precision and recall scores across all folds
print("Average precision score: %0.2f" % (sum(precision_scores) / len(precision_scores)))
print("Average recall score: %0.2f" % (sum(recall_scores) / len(recall_scores)))

Average precision score: 0.95
Average recall score: 0.95